import type { Product } from './types';

export const products: Product[] = [
  {
    id: "33",
    name: "Coque en silicone pour iPhone",
    description: "Protection souple et colorée",
    fullDescription: "Cette coque en silicone épouse parfaitement les formes de votre iPhone sans l'alourdir. Elle offre une protection simple et efficace contre les rayures et les petits chocs du quotidien.",
    category: "Coque de téléphone",
    price: 800,
    rating: 4.2,
    likes: 150,
    stock: "En stock",
    imageIds: ["product-33"],
    specs: [
        "Silicone souple",
        "Toucher doux",
        "Découpes précises",
        "Plusieurs couleurs disponibles"
    ],
    warranty: "Garantie 3 mois",
    delivery: "Livraison rapide",
  },
  {
    id: "34",
    name: "AirPods Pro (2ème génération)",
    description: "Réduction de bruit active et son immersif",
    fullDescription: "Découvrez une expérience sonore inégalée avec les AirPods Pro de 2ème génération. Profitez d'une réduction de bruit active supérieure et d'un son spatial personnalisé pour une immersion totale.",
    category: "Airpod",
    price: 4000,
    rating: 4.8,
    likes: 350,
    stock: "En stock",
    badge: "Populaire",
    imageIds: ["product-34"],
    specs: [
        "Réduction de bruit active",
        "Audio spatial personnalisé",
        "Boîtier de charge MagSafe",
        "Contrôle tactile"
    ],
    warranty: "Garantie 6 mois",
    delivery: "Livraison rapide",
  },
  {
    id: "35",
    name: "Câble de charge pour iPhone",
    description: "Câble USB vers Lightning robuste",
    fullDescription: "Un câble de charge fiable et durable pour tous vos appareils Apple avec port Lightning. Sa longueur d'un mètre est idéale pour une utilisation à la maison ou au bureau.",
    category: "Câble",
    price: 800,
    rating: 4.5,
    likes: 280,
    stock: "En stock",
    imageIds: ["product-35"],
    specs: [
        "Longueur : 1m",
        "Connecteur : USB-A vers Lightning",
        "Transfert de données",
        "Matériaux résistants"
    ],
    warranty: "Garantie 3 mois",
    delivery: "Livraison rapide",
  },
  {
    id: "36",
    name: "Écran de remplacement pour iPhone XR",
    description: "Kit complet pour réparation",
    fullDescription: "Redonnez vie à votre iPhone XR avec cet écran de remplacement de haute qualité. Le kit inclut tous les outils nécessaires pour une réparation facile et rapide.",
    category: "Téléphonie",
    price: 5000,
    rating: 4.6,
    likes: 95,
    stock: "En stock",
    imageIds: ["product-36"],
    specs: [
        "Type : Liquid Retina HD",
        "Taille : 6.1 pouces",
        "Compatible True Tone",
        "Kit d'outils inclus"
    ],
    warranty: "Garantie 6 mois",
    delivery: "Livraison rapide",
  },
  {
    id: "2",
    name: "iPhone 15 Pro Max",
    description: "Le summum de la technologie Apple.",
    fullDescription: "L'iPhone 15 Pro Max, forgé en titane, est doté de la puce A17 Pro, d'un bouton Action personnalisable et du système photo le plus puissant jamais vu sur iPhone.",
    category: "Téléphonie",
    price: 950000,
    originalPrice: 1050000,
    rating: 4.9,
    likes: 245,
    stock: "En stock",
    badge: "Nouveau",
    imageIds: ["product-2"],
    specs: [
      "Écran Super Retina XDR 6.7\"",
      "Puce A17 Pro",
      "Système photo pro 48 Mpx",
      "Dynamic Island",
      "USB-C avec USB 3"
    ],
    warranty: "Garantie Apple 1 an",
    delivery: "Livraison gratuite sous 24-48h"
  },
  {
    id: "5",
    name: "Apple Watch Series 9 GPS 45mm",
    description: "Écran AMOLED, GPS, Résistant eau",
    fullDescription: "Montre connectée Apple Watch Series 9 avec suivi santé avancé et design élégant. Parfaite pour le fitness et la productivité avec une autonomie optimisée et des fonctionnalités intelligentes.",
    category: "Wearables",
    price: 450000,
    originalPrice: 500000,
    rating: 5,
    likes: 94,
    stock: "En stock",
    badge: "-10%",
    imageIds: ["product-5"],
    specs: [
        "Écran Retina Always-On 45mm",
        "Puce S9 SiP avec Neural Engine",
        "GPS et capteurs santé avancés",
        "Résistant à l'eau jusqu'à 50m",
        "Autonomie jusqu'à 18h",
        "Chargement rapide magnétique",
        "Compatible iPhone iOS 16+",
        "Bracelet sport inclus"
    ],
    warranty: "Garantie Apple 1 an",
    delivery: "Livraison rapide",
  },
  {
    id: "6",
    name: "Coque Renforcée iPhone 15 Pro - Verre Trempé",
    description: "Protection 360°, Anti-choc, Bordures surélevées",
    fullDescription: "Coque de protection premium avec dos en verre trempé 9H et contours TPU renforcés. Protection optimale contre les chutes jusqu'à 3 mètres.",
    category: "Coque de téléphone",
    price: 15000,
    originalPrice: 20000,
    rating: 5,
    likes: 342,
    stock: "En stock",
    badge: "-25%",
    imageIds: ["product-6"],
    specs: [
      "Dos en verre trempé 9H",
      "Contours TPU antichoc",
      "Bordures surélevées caméra et écran",
      "Compatible charge sans fil",
      "Certification drop test 3m",
      "Revêtement oléophobe anti-traces"
    ],
    warranty: "Garantie 1 an",
    delivery: "Livraison rapide",
  },
  {
    id: "7",
    name: "Coque Personnalisée - Tous Modèles",
    description: "Impression HD, Personnalisable, Silicone souple",
    fullDescription: "Créez votre coque unique avec notre service de personnalisation. Impression HD haute qualité sur silicone souple. Compatible avec plus de 200 modèles de smartphones.",
    category: "Coque personnalisée",
    price: 12000,
    rating: 4.5,
    likes: 198,
    stock: "En stock",
    badge: "Nouveau",
    imageIds: ["product-7"],
    specs: [
      "Impression HD haute définition",
      "200+ modèles compatibles",
      "Silicone TPU souple",
      "Personnalisation photo/texte",
      "Résistant aux UV",
      "Délai création 48h"
    ],
    warranty: "Garantie satisfaction 30 jours",
    delivery: "Livraison sous 3-5 jours (après création)",
  },
  {
    id: "8",
    name: "Coque Transparente Ultra Fine - iPhone 14",
    description: "TPU transparent, Ultra fine 0.3mm, Anti-rayures",
    fullDescription: "Coque minimaliste ultra fine qui préserve le design original de votre iPhone. Protection invisible contre rayures et chocs légers.",
    category: "Coque de téléphone",
    price: 8500,
    originalPrice: 10000,
    rating: 4,
    likes: 276,
    stock: "En stock",
    badge: "-15%",
    imageIds: ["product-8"],
    specs: [
      "TPU transparent premium",
      "Épaisseur 0.3mm seulement",
      "Traitement anti-jaunissement",
      "Découpes de précision",
      "Compatible MagSafe",
      "Touch ID/Face ID compatible"
    ],
    warranty: "Garantie 6 mois",
    delivery: "Livraison rapide",
  },
  {
    id: "9",
    name: "Coque Cuir Premium Samsung Galaxy S24",
    description: "Cuir véritable, Porte-cartes intégré, Finition luxe",
    fullDescription: "Élégance et fonctionnalité avec cette coque en cuir véritable. Compartiment porte-cartes intégré et finition artisanale haut de gamme.",
    category: "Coque de téléphone",
    price: 18000,
    rating: 5,
    likes: 89,
    stock: "En stock",
    imageIds: ["product-9"],
    specs: [
      "Cuir véritable italien",
      "2 emplacements cartes",
      "Fonction stand vidéo",
      "Fermeture magnétique",
      "Doublure microfibre",
      "Finition coutures main"
    ],
    warranty: "Garantie 2 ans",
    delivery: "Livraison rapide",
  },
  {
    id: "10",
    name: "Coque Antichoc Military Grade - Xiaomi",
    description: "Norme militaire, Coins renforcés, Support magnétique",
    fullDescription: "Protection militaire certifiée pour votre Xiaomi. Résiste aux chocs extrêmes avec ses 4 coins renforcés et son support magnétique intégré pour voiture.",
    category: "Coque de téléphone",
    price: 10500,
    originalPrice: 15000,
    rating: 4.5,
    likes: 431,
    stock: "En stock",
    badge: "-30%",
    imageIds: ["product-10"],
    specs: [
      "Certification MIL-STD-810G",
      "Protection chutes 4 mètres",
      "4 coins Air Cushion Technology",
      "Support magnétique voiture inclus",
      "Grip antidérapant texturé",
      "Compatible protection écran"
    ],
    warranty: "Garantie à vie",
    delivery: "Livraison rapide",
  },
  {
    id: "11",
    name: "Samsung Galaxy S24 Ultra",
    description: "Le meilleur de Samsung, avec IA",
    fullDescription: "Le Samsung Galaxy S24 Ultra intègre le S Pen, un appareil photo de 200 Mpx et des fonctionnalités Galaxy AI pour une productivité et une créativité inégalées.",
    category: "Téléphonie",
    price: 1100000,
    rating: 4.8,
    likes: 150,
    stock: "En stock",
    badge: "IA",
    imageIds: ["product-11"],
    specs: ["Écran Dynamic AMOLED 2X 6.8\"", "Processeur Snapdragon 8 Gen 3", "Appareil photo 200MP", "S Pen intégré"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 24h"
  },
  {
    id: "12",
    name: "Google Pixel 8 Pro",
    description: "La photo intelligente par Google",
    fullDescription: "Le Google Pixel 8 Pro est le smartphone le plus avancé de Google, avec un appareil photo exceptionnel et des fonctionnalités d'IA exclusives qui simplifient votre quotidien.",
    category: "Téléphonie",
    price: 850000,
    rating: 4.7,
    likes: 120,
    stock: "En stock",
    badge: "Google AI",
    imageIds: ["product-12"],
    specs: ["Écran Super Actua 6.7\"", "Processeur Google Tensor G3", "Triple appareil photo 50MP", "VPN par Google One inclus"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 24h"
  },
  {
    id: "13",
    name: "Xiaomi 14 Pro",
    description: "Partenariat Leica pour la photo",
    fullDescription: "Le Xiaomi 14 Pro, conçu avec Leica, offre une expérience photographique de niveau professionnel. Son design élégant et ses performances de pointe en font un choix incontournable.",
    category: "Téléphonie",
    price: 750000,
    rating: 4.6,
    likes: 95,
    stock: "En stock",
    imageIds: ["product-13"],
    specs: ["Écran AMOLED 6.73\"", "Processeur Snapdragon 8 Gen 3", "Optiques Leica Summilux", "HyperCharge 120W"],
    warranty: "Garantie 1 an",
    delivery: "Livraison en 48h"
  },
  {
    id: "14",
    name: "Airpods Pro 2",
    description: "Réduction de bruit active et son spatial",
    fullDescription: "Les AirPods Pro (2ᵉ génération) offrent une Réduction active du bruit jusqu’à 2x plus efficace, un mode Transparence adaptative et l’Audio spatial personnalisé avec suivi dynamique des mouvements de la tête.",
    category: "Airpod",
    price: 180000,
    rating: 4.9,
    likes: 250,
    stock: "En stock",
    imageIds: ["product-14"],
    specs: ["Puce H2 d'Apple", "Réduction active du bruit", "Boîtier de charge MagSafe (USB-C)", "Jusqu'à 6h d'écoute"],
    warranty: "Garantie Apple 1 an",
    delivery: "Livraison en 24h"
  },
  {
    id: "15",
    name: "Sony WF-1000XM5",
    description: "Le silence. Le son. Par Sony.",
    fullDescription: "Les WF-1000XM5 sont dotés d'une technologie de pointe pour offrir une qualité sonore supérieure et la meilleure réduction de bruit du marché.",
    category: "Airpod",
    price: 220000,
    rating: 4.8,
    likes: 180,
    stock: "En stock",
    imageIds: ["product-15"],
    specs: ["Processeur V2 intégré", "Dynamic Driver X", "Qualité d'appel exceptionnelle", "8h d'autonomie"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  },
  {
    id: "16",
    name: "Bose QuietComfort Ultra Earbuds",
    description: "Réduction de bruit immersive",
    fullDescription: "Ces écouteurs offrent un son spatialisé et une réduction de bruit de classe mondiale pour une expérience d'écoute totalement immersive.",
    category: "Airpod",
    price: 250000,
    rating: 4.7,
    likes: 160,
    stock: "En stock",
    imageIds: ["product-16"],
    specs: ["Son immersif Bose", "Réduction de bruit CustomTune", "Jusqu'à 6h d'autonomie", "Confort et stabilité"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  },
  {
    id: "17",
    name: "Samsung Galaxy Buds2 Pro",
    description: "Qualité sonore Hi-Fi 24 bits",
    fullDescription: "Plongez au cœur de vos contenus préférés avec le son haute-fidélité des Galaxy Buds2 Pro. Leur technologie de réduction active de bruit intelligente vous isole du monde extérieur.",
    category: "Airpod",
    price: 150000,
    rating: 4.5,
    likes: 130,
    stock: "En stock",
    imageIds: ["product-17"],
    specs: ["Son Hi-Fi 24 bits", "Réduction de bruit active intelligente", "Design ergonomique", "Audio 360"],
    warranty: "Garantie 1 an",
    delivery: "Livraison en 24h"
  },
  {
    id: "18",
    name: "Cable USB-C vers Lightning (2m)",
    description: "Certifié MFi, charge rapide",
    fullDescription: "Ce câble robuste et certifié par Apple vous permet de recharger rapidement votre iPhone et de synchroniser vos données en toute sécurité. Longueur de 2 mètres pour plus de flexibilité.",
    category: "Câble",
    price: 15000,
    rating: 4.8,
    likes: 200,
    stock: "En stock",
    imageIds: ["product-18"],
    specs: ["Longueur 2m", "Certifié MFi", "Compatible Power Delivery", "Transfert de données 480 Mbps"],
    warranty: "Garantie 1 an",
    delivery: "Livraison en 24h"
  },
  {
    id: "19",
    name: "Cable HDMI 2.1 8K (3m)",
    description: "Ultra Haute Vitesse, 48Gbps, eARC",
    fullDescription: "Profitez d'une qualité d'image et de son optimale avec ce câble HDMI 2.1. Il supporte les résolutions 8K à 60Hz et 4K à 120Hz, idéal pour les consoles nouvelle génération et les TV haut de gamme.",
    category: "Câble",
    price: 20000,
    rating: 4.9,
    likes: 150,
    stock: "En stock",
    imageIds: ["product-19"],
    specs: ["HDMI 2.1 certifié", "Bande passante 48 Gbps", "Support 8K@60Hz, 4K@120Hz", "Dynamic HDR, eARC"],
    warranty: "Garantie à vie",
    delivery: "Livraison en 48h"
  },
  {
    id: "20",
    name: "Chargeur Anker 100W GaNPrime",
    description: "4 ports (3x USB-C, 1x USB-A)",
    fullDescription: "Un seul chargeur pour tous vos appareils. Grâce à la technologie GaNPrime, ce chargeur compact de 100W peut recharger rapidement votre MacBook, iPhone, et autres appareils simultanément.",
    category: "Câble",
    price: 45000,
    rating: 4.9,
    likes: 180,
    stock: "En stock",
    badge: "Puissant",
    imageIds: ["product-20"],
    specs: ["Puissance 100W", "Technologie GaNPrime", "3 ports USB-C, 1 port USB-A", "ActiveShield 2.0 pour la sécurité"],
    warranty: "Garantie 18 mois",
    delivery: "Livraison en 24h"
  },
  {
    id: "21",
    name: "Hub USB-C 7-en-1 Satechi",
    description: "HDMI 4K, Lecteur SD, Ethernet",
    fullDescription: "Étendez la connectivité de votre ordinateur portable avec ce hub USB-C complet. Il offre un port HDMI 4K, un port Ethernet, des lecteurs de cartes SD/microSD et plusieurs ports USB.",
    category: "Câble",
    price: 55000,
    rating: 4.7,
    likes: 110,
    stock: "En stock",
    imageIds: ["product-21"],
    specs: ["HDMI 4K @ 60Hz", "Gigabit Ethernet", "Lecteur SD/MicroSD", "2x USB-A 3.0", "USB-C Power Delivery"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  },
  {
    id: "22",
    name: "Enceinte Bluetooth JBL Charge 5",
    description: "Son Pro Original JBL, 20h d'autonomie",
    fullDescription: "L'enceinte JBL Charge 5 offre un Son Pro Original JBL audacieux. Avec son autonomie de 20 heures et son design étanche à l'eau et à la poussière (IP67), la fête vous suit partout.",
    category: "Enceinte",
    price: 110000,
    rating: 4.8,
    likes: 300,
    stock: "En stock",
    imageIds: ["product-22"],
    specs: ["Son Pro Original JBL", "20h d'autonomie", "Étanchéité IP67", "Mode PartyBoost", "Powerbank intégré"],
    warranty: "Garantie 1 an",
    delivery: "Livraison en 24h"
  },
  {
    id: "23",
    name: "Enceinte connectée Sonos One",
    description: "Son riche et puissant, contrôle vocal",
    fullDescription: "La Sonos One est l'enceinte connectée idéale pour les amateurs de musique. Profitez d'un son riche et puissant, et contrôlez votre musique avec votre voix, l'application Sonos, Apple AirPlay 2, et plus encore.",
    category: "Enceinte",
    price: 160000,
    rating: 4.9,
    likes: 220,
    stock: "En stock",
    imageIds: ["product-23"],
    specs: ["Son haute-fidélité", "Contrôle vocal (Google Assistant, Alexa)", "Design compact", "Résistante à l'humidité"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  },
  {
    id: "24",
    name: "Barre de son Samsung HW-Q990C",
    description: "Dolby Atmos sans fil, 11.1.4 canaux",
    fullDescription: "Vivez une expérience sonore cinématographique immersive avec la barre de son HW-Q990C. Le premier Dolby Atmos sans fil au monde vous plonge au cœur de l'action.",
    category: "Enceinte",
    price: 900000,
    rating: 5,
    likes: 90,
    stock: "En stock",
    badge: "Cinéma",
    imageIds: ["product-24"],
    specs: ["11.1.4 canaux", "Dolby Atmos sans fil", "Q-Symphony", "SpaceFit Sound Pro"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison et installation offertes"
  },
  {
    id: "25",
    name: "Enceinte portable Bose SoundLink Flex",
    description: "Son clair et profond, étanche",
    fullDescription: "L'enceinte SoundLink Flex est conçue pour vous accompagner partout. Étanche, robuste et dotée de la technologie PositionIQ™, elle offre un son incroyable, quelle que soit sa position.",
    category: "Enceinte",
    price: 95000,
    rating: 4.7,
    likes: 180,
    stock: "En stock",
    imageIds: ["product-25"],
    specs: ["Technologie PositionIQ™", "Étanche et flotte (IP67)", "12h d'autonomie", "Jumelage stéréo"],
    warranty: "Garantie 1 an",
    delivery: "Livraison en 24h"
  },
  {
    id: "26",
    name: "Dell XPS 15",
    description: "Écran OLED, performances créatives",
    fullDescription: "Le Dell XPS 15 est le parfait équilibre entre puissance et portabilité. Avec son superbe écran OLED et ses processeurs Intel Core, il est idéal pour les créateurs de contenu.",
    category: "PC",
    price: 1800000,
    rating: 4.8,
    likes: 130,
    stock: "En stock",
    imageIds: ["product-26"],
    specs: ["Processeur Intel Core i9", "NVIDIA GeForce RTX 40-series", "Écran OLED 3.5K", "Châssis en aluminium"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  },
  {
    id: "27",
    name: "HP Spectre x360",
    description: "Design 2-en-1, écran tactile",
    fullDescription: "Le HP Spectre x360 est un ordinateur portable convertible qui allie un design somptueux à des performances impressionnantes. Passez facilement du mode ordinateur portable au mode tablette.",
    category: "PC",
    price: 1300000,
    rating: 4.7,
    likes: 115,
    stock: "En stock",
    imageIds: ["product-27"],
    specs: ["Processeur Intel Core Ultra 7", "Écran OLED tactile 14\"", "Design convertible 360°", "Stylet inclus"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 24h"
  },
  {
    id: "28",
    name: "Razer Blade 16",
    description: "Puissance de jeu maximale, écran Mini-LED",
    fullDescription: "Plus puissant que jamais, le Razer Blade 16 est le summum du PC portable gaming. Profitez d'un écran bi-mode Mini-LED unique et de performances graphiques sans compromis.",
    category: "PC",
    price: 3500000,
    rating: 4.9,
    likes: 85,
    stock: "En stock",
    badge: "Gaming Ultime",
    imageIds: ["product-28"],
    specs: ["Intel Core i9-14900HX", "NVIDIA RTX 4090", "Écran bi-mode Mini-LED (4K 120Hz/FHD+ 240Hz)", "Chambre à vapeur"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 3-5 jours"
  },
  {
    id: "29",
    name: "Réfrigérateur connecté Samsung Family Hub",
    description: "Écran tactile, gestion des aliments",
    fullDescription: "Le Family Hub est bien plus qu'un réfrigérateur. Son écran intégré vous permet de gérer vos courses, d'écouter de la musique, de partager des mémos et de voir à l'intérieur sans ouvrir la porte.",
    category: "Electroménager",
    price: 2500000,
    rating: 4.7,
    likes: 70,
    stock: "En stock",
    imageIds: ["product-29"],
    specs: ["Capacité 611L", "Écran tactile 21.5\"", "Caméras internes", "Distributeur d'eau et de glace"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison et installation offertes"
  },
  {
    id: "30",
    name: "Aspirateur robot iRobot Roomba j7+",
    description: "Vidage automatique, évite les obstacles",
    fullDescription: "Le Roomba j7+ est si intelligent qu'il reconnaît et évite les obstacles comme les déjections d'animaux ou les câbles. Il vide même son bac tout seul pour que vous n'ayez pas à y penser pendant des mois.",
    category: "Electroménager",
    price: 650000,
    rating: 4.8,
    likes: 140,
    stock: "En stock",
    imageIds: ["product-30"],
    specs: ["Navigation PrecisionVision", "Système d'autovidage Clean Base", "Aspiration surpuissante", "Suggestions personnalisées"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  },
  {
    id: "31",
    name: "Machine à café Nespresso Vertuo Next",
    description: "5 tailles de tasses, café de qualité",
    fullDescription: "La Vertuo Next sublime votre expérience café. Elle lit le code-barres de chaque capsule pour ajuster les paramètres d'extraction et vous offrir un café parfait, de l'Espresso au Mug.",
    category: "Electroménager",
    price: 120000,
    rating: 4.6,
    likes: 210,
    stock: "En stock",
    imageIds: ["product-31"],
    specs: ["Technologie Centrifusion™", "5 tailles de café", "Connectivité Bluetooth et Wi-Fi", "Design compact"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 24h"
  },
  {
    id: "32",
    name: "Friteuse à air Philips Airfryer XXL",
    description: "Cuit, grille, rôtit et frit avec peu d'huile",
    fullDescription: "L'Airfryer XXL de Philips utilise de l'air chaud pour cuire vos aliments préférés avec jusqu'à 90% de matières grasses en moins. Sa grande capacité est parfaite pour les repas familiaux.",
    category: "Electroménager",
    price: 200000,
    rating: 4.9,
    likes: 350,
    stock: "En stock",
    badge: "Best-seller",
    imageIds: ["product-32"],
    specs: ["Technologie Rapid Air", "Capacité XXL (1.4kg)", "Technologie Fat Removal", "Écran digital avec 5 programmes"],
    warranty: "Garantie 2 ans",
    delivery: "Livraison en 48h"
  }
];
