import type { Product } from './types';

export const products: Product[] = [
  {
    id: "1",
    name: "MacBook Pro 14\" M3 - 512GB SSD",
    description: "Puce M3, 16GB RAM, 512GB SSD",
    fullDescription: "Le MacBook Pro 14 pouces avec puce M3 offre des performances exceptionnelles pour les professionnels créatifs. Avec son écran Liquid Retina XDR, son autonomie de 17 heures et son design compact, c'est l'ordinateur portable idéal pour le travail intensif.",
    category: "Informatique",
    price: 1450000,
    originalPrice: 1700000,
    rating: 4.5,
    likes: 127,
    stock: "En stock",
    badge: "-15%",
    imageIds: ["product-1"],
    specs: [
        "Puce Apple M3 (8 cœurs CPU, 10 cœurs GPU)",
        "16 Go de mémoire unifiée",
        "512 Go de stockage SSD",
        "Écran Liquid Retina XDR 14,2 pouces",
        "Autonomie jusqu'à 17 heures",
        "3 ports Thunderbolt 4, HDMI, lecteur carte SD",
        "Caméra FaceTime HD 1080p",
        "Poids : 1,55 kg"
    ],
    warranty: "Garantie Apple 1 an + Extension possible",
    delivery: "Livraison gratuite sous 2-3 jours ouvrés",
  },
  {
    id: "2",
    name: "iPhone 15 Pro Max 256GB - Titane Bleu",
    description: "Puce A17 Pro, 6.7\", Triple caméra",
    fullDescription: "L'iPhone 15 Pro Max redéfinit ce qu'un smartphone peut faire. Avec son nouveau design en titane, sa puce A17 Pro et son système de caméras avancé, c'est le summum de la technologie mobile.",
    category: "Téléphonie",
    price: 950000,
    rating: 5,
    likes: 89,
    stock: "En stock",
    badge: "Nouveau",
    imageIds: ["product-2"],
    specs: [
        "Puce A17 Pro (3 nm)",
        "Écran Super Retina XDR 6,7 pouces ProMotion",
        "Système triple caméra 48 MP + 12 MP + 12 MP",
        "Zoom optique 5x",
        "Batterie autonomie journée complète",
        "USB-C avec USB 3.0",
        "Face ID, Crash Detection, SOS d'urgence",
        "Résistant eau/poussière IP68"
    ],
    warranty: "Garantie Apple 1 an",
    delivery: "Livraison gratuite sous 24-48h",
  },
  {
    id: "3",
    name: "PC Gaming RTX 4070 - Intel i7-13700K",
    description: "RTX 4070, Intel i7, 32GB RAM",
    fullDescription: "PC Gaming haute performance équipé des dernières technologies pour les joueurs exigeants. Configuration optimisée pour le gaming 4K et le streaming avec une carte graphique RTX 4070 et un processeur Intel i7-13700K.",
    category: "Gaming",
    price: 2200000,
    originalPrice: 2750000,
    rating: 5,
    likes: 156,
    stock: "En stock",
    badge: "-20%",
    imageIds: ["product-3"],
    specs: [
        "Processeur Intel Core i7-13700K (16 cœurs)",
        "Carte graphique NVIDIA GeForce RTX 4070 12GB",
        "32 Go RAM DDR5-5600 MHz",
        "SSD NVMe 1TB PCIe 4.0",
        "Alimentation 850W 80+ Gold",
        "Refroidissement liquide AIO 240mm",
        "Carte mère Z790 ATX",
        "Boîtier gaming avec RGB"
    ],
    warranty: "Garantie constructeur 2 ans + Support technique",
    delivery: "Livraison gratuite sous 3-5 jours ouvrés",
  },
  {
    id: "4",
    name: "Smart TV 4K UHD 55\" - Samsung QLED",
    description: "4K UHD, Smart TV, 55 pouces",
    fullDescription: "Téléviseur 4K UHD Samsung QLED 55 pouces avec technologie Smart pour une expérience de visionnage premium. Idéal pour le home cinéma avec un excellent contraste et des couleurs vives.",
    category: "Image & Son",
    price: 850000,
    rating: 4.5,
    likes: 203,
    stock: "En stock",
    badge: "Nouveau",
    imageIds: ["product-4"],
    specs: [
        "Écran QLED 4K UHD 55 pouces",
        "Processeur Quantum Dot 4K",
        "Smart TV Tizen OS",
        "HDR10+ et HDR10+ Adaptive",
        "Son Dolby Atmos",
        "Wi-Fi 6 et Bluetooth 5.2",
        "4 ports HDMI 2.1",
        "Contrôle vocal Bixby et Alexa"
    ],
    warranty: "Garantie Samsung 2 ans",
    delivery: "Livraison et installation gratuites sous 48h",
  },
  {
    id: "5",
    name: "Apple Watch Series 9 GPS 45mm",
    description: "Écran AMOLED, GPS, Résistant eau",
    fullDescription: "Montre connectée Apple Watch Series 9 avec suivi santé avancé et design élégant. Parfaite pour le fitness et la productivité avec une autonomie optimisée et des fonctionnalités intelligentes.",
    category: "Wearables",
    price: 450000,
    originalPrice: 500000,
    rating: 5,
    likes: 94,
    stock: "En stock",
    badge: "-10%",
    imageIds: ["product-5"],
    specs: [
        "Écran Retina Always-On 45mm",
        "Puce S9 SiP avec Neural Engine",
        "GPS et capteurs santé avancés",
        "Résistant à l'eau jusqu'à 50m",
        "Autonomie jusqu'à 18h",
        "Chargement rapide magnétique",
        "Compatible iPhone iOS 16+",
        "Bracelet sport inclus"
    ],
    warranty: "Garantie Apple 1 an",
    delivery: "Livraison gratuite sous 24-48h",
  },
  {
    id: "6",
    name: "Coque Renforcée iPhone 15 Pro - Verre Trempé",
    description: "Protection 360°, Anti-choc, Bordures surélevées",
    fullDescription: "Coque de protection premium avec dos en verre trempé 9H et contours TPU renforcés. Protection optimale contre les chutes jusqu'à 3 mètres.",
    category: "Téléphonie",
    price: 15000,
    originalPrice: 20000,
    rating: 5,
    likes: 342,
    stock: "En stock",
    badge: "-25%",
    imageIds: ["product-6"],
    specs: [
      "Dos en verre trempé 9H",
      "Contours TPU antichoc",
      "Bordures surélevées caméra et écran",
      "Compatible charge sans fil",
      "Certification drop test 3m",
      "Revêtement oléophobe anti-traces"
    ],
    warranty: "Garantie 1 an",
    delivery: "Livraison gratuite sous 24-48h",
  },
  {
    id: "7",
    name: "Coque Personnalisée - Tous Modèles",
    description: "Impression HD, Personnalisable, Silicone souple",
    fullDescription: "Créez votre coque unique avec notre service de personnalisation. Impression HD haute qualité sur silicone souple. Compatible avec plus de 200 modèles de smartphones.",
    category: "Téléphonie",
    price: 12000,
    rating: 4.5,
    likes: 198,
    stock: "En stock",
    badge: "Nouveau",
    imageIds: ["product-7"],
    specs: [
      "Impression HD haute définition",
      "200+ modèles compatibles",
      "Silicone TPU souple",
      "Personnalisation photo/texte",
      "Résistant aux UV",
      "Délai création 48h"
    ],
    warranty: "Garantie satisfaction 30 jours",
    delivery: "Livraison sous 3-5 jours (après création)",
  },
  {
    id: "8",
    name: "Coque Transparente Ultra Fine - iPhone 14",
    description: "TPU transparent, Ultra fine 0.3mm, Anti-rayures",
    fullDescription: "Coque minimaliste ultra fine qui préserve le design original de votre iPhone. Protection invisible contre rayures et chocs légers.",
    category: "Téléphonie",
    price: 8500,
    originalPrice: 10000,
    rating: 4,
    likes: 276,
    stock: "En stock",
    badge: "-15%",
    imageIds: ["product-8"],
    specs: [
      "TPU transparent premium",
      "Épaisseur 0.3mm seulement",
      "Traitement anti-jaunissement",
      "Découpes de précision",
      "Compatible MagSafe",
      "Touch ID/Face ID compatible"
    ],
    warranty: "Garantie 6 mois",
    delivery: "Livraison gratuite sous 24h",
  },
  {
    id: "9",
    name: "Coque Cuir Premium Samsung Galaxy S24",
    description: "Cuir véritable, Porte-cartes intégré, Finition luxe",
    fullDescription: "Élégance et fonctionnalité avec cette coque en cuir véritable. Compartiment porte-cartes intégré et finition artisanale haut de gamme.",
    category: "Téléphonie",
    price: 18000,
    rating: 5,
    likes: 89,
    stock: "En stock",
    imageIds: ["product-9"],
    specs: [
      "Cuir véritable italien",
      "2 emplacements cartes",
      "Fonction stand vidéo",
      "Fermeture magnétique",
      "Doublure microfibre",
      "Finition coutures main"
    ],
    warranty: "Garantie 2 ans",
    delivery: "Livraison gratuite sous 48h",
  },
  {
    id: "10",
    name: "Coque Antichoc Military Grade - Xiaomi",
    description: "Norme militaire, Coins renforcés, Support magnétique",
    fullDescription: "Protection militaire certifiée pour votre Xiaomi. Résiste aux chocs extrêmes avec ses 4 coins renforcés et son support magnétique intégré pour voiture.",
    category: "Téléphonie",
    price: 10500,
    originalPrice: 15000,
    rating: 4.5,
    likes: 431,
    stock: "En stock",
    badge: "-30%",
    imageIds: ["product-10"],
    specs: [
      "Certification MIL-STD-810G",
      "Protection chutes 4 mètres",
      "4 coins Air Cushion Technology",
      "Support magnétique voiture inclus",
      "Grip antidérapant texturé",
      "Compatible protection écran"
    ],
    warranty: "Garantie à vie",
    delivery: "Livraison gratuite sous 24-48h",
  }
];
